### ISSUE TITLE
Invalid device ordinal error

### ISSUE THREAD

**Issue by lmohit95** [Hsword/Hetu#61]
Hello,
I am running HET on criteo dataset on a single GPU node by setting HETU_VERSION = 'gpu' in **HYBRID** mode. I ran  `bash examples/ctr/tests/hybrid_wdl_criteo.sh, but I am getting the following error:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/89669946/206828966-074e3bee-5d06-4656-ad4d-4afcf7fd057c.png">

I tried printing dev_id in gpu_runtime.cc. It always gives 1, 2, 3 instead of 0.

This is my configuration file

```
shared :
  DMLC_PS_ROOT_URI : 127.0.0.1
  DMLC_PS_ROOT_PORT : 13100
  DMLC_NUM_WORKER : 2
  DMLC_NUM_SERVER : 1
  DMLC_PS_VAN_TYPE : p3
launch :
  worker : 2
  server : 1
  scheduler : true
nodes:
  - host: lmohit95
    servers: 1
    workers: 2
    chief: true

```

**Comment by Hankpipi** [comment]
Hi @lmohit95, `hybrid_wdl_criteo.sh` updated recently, which will not depend on configuration file anymore. Please run this script to run HET on a single GPU:
```
heturun -s 1 -w 1 python examples/ctr/run_hetu.py --model wdl_criteo --val --comm Hybrid --cache lfuopt --bound 3
```

Besides, there are still some errors when I run `hybrid_wdl_criteo.sh`, but it will be fixed by #60. Please wait for its merge and pull the new code. cc @Hsword.

**Comment by Hsword** [comment]
The PR #60 has been merged. Please inform us if there is any further questions.

**Comment by lmohit95** [comment]
Thank you. It works with a single worker.
1. When I run `heturun -s 1 -w 1 python examples/ctr/run_hetu.py --model wdl_criteo --val` (without any hybrid/ps properties), each epoch runs for 145 hrs compare to 3 to 4 min for each epoch while using hybrid. Is such a significant difference in runtime times valid?

2. By launching more workers on a single GPU using 
`heturun -s 2 -w 1 python examples/ctr/run_hetu.py --model wdl_criteo --val --comm Hybrid --cache lfuopt --bound 3`,
will the training work be divided among 2 workers on a single GPU?
Currently. I get this error on running the above command

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/89669946/206866139-bef48ef0-6cfa-4cb8-8dc9-b56ccf60200a.png">

3. I am also trying to setup multiple GPU nodes to perform distributed training on wdl_criteo dataset. In that case, I think I will need config file. Can you suggest how I can do distributed training using different machines?

**Comment by Hankpipi** [comment]
For the first two questions, I tried to run the scripts given, but it worked well in my enviroment. Please try to check your work environment.

To run distributed training using different machines, please refer to examples in `examples/runner/`. I'm not sure if it works well now, so please inform us if there is any errors.

**Comment by Hsword** [comment]
1. It seems like you are trying to use single GPU training (without hybrid or ps). In that case, we suggest to use the local execution mode, rather than ```heturun```.
2. Colocating 2 workers on a single GPU is not a discouraged practice.
Both Q1 and Q2 will lead to undefined behaviors. Please strictly follow our usage instructions for correctness and efficiency.

3. For multiple nodes, please refer to #63 as described by @Hankpipi .
